### ISSUE TITLE
Refactoring log-extractor

### ISSUE THREAD

**Issue by KKoukiou** [cynepco3hahue/log-extractor#19]
As you know, I would like to integrate this script in our Jenkins jobs, so as to re-factor the logs in the end of each run, as a post-build task.
Because log sizes can be quite big, ~30GB, we need to make sure we manipulate with them efficiently and avoid duplication of files.
Thus I would like to raise here a few points, and if you agree, re-factor the log-extractor to make it more generic regarding the file type manipulation, more modular and with less parameters.

* `--source` parameter: The input logs right now can be either downloaded from Jenkins or be local archive downloaded from Jobs artifacts. I need to add one more parameter, to allow parsing the $WORKSPACE in Jenkins Jobs instead of archives because in Jenkins we don't have generated archives, at the point I am parsing the logs. And of course archiving -> unarchiving is completely redundant. Thus we already have 3 input methods, and a lot of relevant parameters, which can be merged into one.
`--build`, `--job`, `--skip-download`, `--local-log-file`, (future local-log-dir) all can be merged into `--source` parameter.
Then we can check parameter value, if it's local dir, local file  or url and act accordingly.

* extract_all: The whole extracting and moving of the files in this method is not needed. Regardless if we are dealing with zip files, tar.gz files or directories we can list and open files there without extracting entire archive which is time consuming and taking up space. I believe we should skip extraction and just parse the relevant files in-place using following modules [zipfile](https://docs.python.org/2/library/zipfile.html) & [tarfile](https://docs.python.org/2/library/tarfile.html).

What do you think?

**Comment by KKoukiou** [comment]
adding for feedback @StLuke @myakove

**Comment by StLuke** [comment]
+1
archive is ~30GB note: parse only failed tests (nobody cares about passed tests most of the time) and clean after yourself unused logs/archives

**Comment by cynepco3hahue** [comment]
@KKoukiou - I agree with the first one, it will make tool more generic
- About second one we will need to check two things
  - if it will work when you have nested archives
  - if it will not increase parsing time, I do not sure about zipfile and tarfile library performance

@StLuke It a little problematic to parse only failed tests, because code goes in series from the first test to the last one. Can you provide some pseudo-code for the algorithm?

**Comment by StLuke** [comment]
@cynepco3hahue yeah I would not recommend investing time on parsing just failed, rather removing the successfull tests from logs after parsing is done to save space
