### ISSUE TITLE
Unnecessarily wasted storage space

### ISSUE THREAD

**Issue by KwisatzHaderach** [cynepco3hahue/log-extractor#6]
It might be better to remove all unnecessary content after extraction.
It takes 17 GB of my storage space from which my desired folder, and the only thing I actually need, takes 223 MB.

Maybe we can have some option on this? Or something like remove everything else (apart from desired folder) if team is specified.

I don't mind downloading the zip, neither I mind having that space taken for the time it takes to parse everything, but it's not necessary to have those files later on.

**Comment by cynepco3hahue** [comment]
Will add the option to remove unneeded files.
